package com.example.foodapp.pojo

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "mealInformation")
data class Meal(
    val dateModified: Any?,
    @PrimaryKey
    val idMeal: String,
    val strArea: String?,
    val strCategory: String?,
    val strCreativeCommonsConfirmed: Any?,
    val strDrinkAlternate: Any?,
    val strImageSource: Any?,
    val strIngredient1: String?,
    val strIngredient10: Any?,
    val strIngredient11: Any?,
    val strIngredient12: Any?,
    val strIngredient13: Any?,
    val strIngredient14: Any?,
    val strIngredient15: Any?,
    val strIngredient16: Any?,
    val strIngredient17: Any?,
    val strIngredient18: Any?,
    val strIngredient19: Any?,
    val strIngredient2: String?,
    val strIngredient20: Any?,
    val strIngredient3: String?,
    val strIngredient4: String?,
    val strIngredient5: Any?,
    val strIngredient6: Any?,
    val strIngredient7: Any?,
    val strIngredient8: Any?,
    val strIngredient9: Any?,
    val strInstructions: String?,
    val strMeal: String?,
    val strMealThumb: String?,
    val strMeasure1: String?,
    val strMeasure10: Any?,
    val strMeasure11: Any?,
    val strMeasure12: Any?,
    val strMeasure13: Any?,
    val strMeasure14: Any?,
    val strMeasure15: Any?,
    val strMeasure16: Any?,
    val strMeasure17: Any?,
    val strMeasure18: Any?,
    val strMeasure19: Any?,
    val strMeasure2: String?,
    val strMeasure20: Any?,
    val strMeasure3: String?,
    val strMeasure4: String?,
    val strMeasure5: Any?,
    val strMeasure6: Any?,
    val strMeasure7: Any?,
    val strMeasure8: Any?,
    val strMeasure9: Any?,
    val strSource: Any?,
    val strTags: String?,
    val strYoutube: String?
)